version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    volumes:
      - ./user-service:/app
    environment:
      FLASK_ENV: development
      DATABASE_URL: "postgresql://user:password@db:5432/mydb"
    depends_on:
      db:
        condition: service_healthy

  order-service:
    build: ./order-service
    ports:
      - "5001:5001"
    volumes:
      - ./order-service:/app
    environment:
      FLASK_ENV: development
      DATABASE_URL: "postgresql://user:password@db:5432/mydb"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
